import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Google Review & Rating Scanner" },
      { name: "description", content: "The terms that govern use of the Google Review & Rating Scanner." },
      { property: "og:title", content: "Terms of Service — Google Review & Rating Scanner" },
      { property: "og:description", content: "The terms that govern use of the Google Review & Rating Scanner." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: TermsPage,
});

const sections: { h: string; body: string[] }[] = [
  {
    h: "1. The Service",
    body: [
      "Google Review & Rating Scanner (“the Service”), operated by Removal Work Solution, helps you retrieve publicly available Google review data, analyse it for policy-relevant risk, and prepare reports and reply drafts.",
      "The Service is independent and is not affiliated with, endorsed by, or sponsored by Google. “Google” and related marks belong to Google LLC.",
    ],
  },
  {
    h: "2. Your account",
    body: [
      "You are responsible for keeping your sign-in credentials confidential and for all activity under your account.",
      "Accounts are created by the administrator. Public sign-up is not available.",
    ],
  },
  {
    h: "3. Acceptable use",
    body: [
      "You may use the Service only for businesses you own, manage, or are authorised to act for.",
      "You must not use the Service to harass reviewers, submit false or misleading reports to Google, scrape data beyond what the Service provides, or attempt to bypass security or usage limits.",
      "We may suspend access for misuse.",
    ],
  },
  {
    h: "4. No guarantee of removal",
    body: [
      "The Service identifies potentially policy-relevant content and helps you use Google's official reporting paths. Only Google decides whether a review is removed. We do not and cannot guarantee any removal, outcome or timeline.",
      "A negative review is not automatically a policy violation. Risk analysis is an aid to your judgement, not a determination of fact.",
    ],
  },
  {
    h: "5. AI-generated content",
    body: [
      "Risk analyses, summaries and reply drafts are generated by AI and may be incomplete or wrong. You are responsible for reviewing them before acting on them. Nothing is posted, reported or sent automatically.",
    ],
  },
  {
    h: "6. Third-party data and limits",
    body: [
      "Review and business data comes from the Google Places API and is subject to Google's terms and availability limits (for example, only a limited number of reviews may be returned). We are not responsible for the accuracy, availability or completeness of third-party data.",
    ],
  },
  {
    h: "7. Intellectual property",
    body: [
      "The Service, its design and its software belong to Removal Work Solution. Reviews remain the content of their authors. Your reports and drafts are yours to use.",
    ],
  },
  {
    h: "8. Disclaimers and liability",
    body: [
      "The Service is provided “as is” without warranties of any kind. To the maximum extent permitted by law, we are not liable for indirect or consequential losses, lost profits, or decisions made based on AI output or third-party data.",
    ],
  },
  {
    h: "9. Changes and termination",
    body: [
      "We may update these terms; the current version is always on this page. You may stop using the Service at any time and request account deletion via removalwork59@gmail.com.",
    ],
  },
  {
    h: "10. Contact",
    body: ["Questions about these terms: removalwork59@gmail.com."],
  },
];

function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-card-border bg-card/60">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-4">
          <Link to="/" className="font-bold text-primary">Review Intelligence</Link>
          <Link to="/privacy" className="text-sm text-muted-foreground hover:text-foreground">Privacy Policy</Link>
        </div>
      </header>
      <main className="mx-auto max-w-3xl px-4 py-10">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: October 2026</p>
        <div className="mt-8 space-y-8">
          {sections.map((s) => (
            <section key={s.h} className="surface p-6">
              <h2 className="text-lg font-semibold">{s.h}</h2>
              <div className="mt-3 space-y-2 text-sm leading-relaxed text-muted-foreground">
                {s.body.map((p, i) => <p key={i}>{p}</p>)}
              </div>
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
