/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports.$id'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiBusinessIdRouteImport } from './routes/api/business/$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiReportsIndexRouteImport } from './routes/api/reports/index'
import { Route as ApiReportsIdRouteImport } from './routes/api/reports/$id'
import { Route as ApiReviewsIdRouteImport } from './routes/api/reviews/$id'
import { Route as ApiScanIndexRouteImport } from './routes/api/scan/index'
import { Route as ApiScanIdRouteImport } from './routes/api/scan/$id'
import { Route as ApiScansIndexRouteImport } from './routes/api/scans/index'
import { Route as ApiScansIdRouteImport } from './routes/api/scans/$id'
import { Route as ApiSettingsIndexRouteImport } from './routes/api/settings/index'
import { Route as ApiSettingsStatusRouteImport } from './routes/api/settings/status'
import { Route as ApiReportsIdDownloadRouteImport } from './routes/api/reports/$id.download'
import { Route as ApiReviewsIdAnalysisRouteImport } from './routes/api/reviews/$id.analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessIdRoute = ApiBusinessIdRouteImport.update({
  id: '/api/business/$id',
  path: '/api/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIndexRoute = ApiReportsIndexRouteImport.update({
  id: '/api/reports/',
  path: '/api/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdRoute = ApiReportsIdRouteImport.update({
  id: '/api/reports/$id',
  path: '/api/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsIdRoute = ApiReviewsIdRouteImport.update({
  id: '/api/reviews/$id',
  path: '/api/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanIndexRoute = ApiScanIndexRouteImport.update({
  id: '/api/scan/',
  path: '/api/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanIdRoute = ApiScanIdRouteImport.update({
  id: '/api/scan/$id',
  path: '/api/scan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScansIndexRoute = ApiScansIndexRouteImport.update({
  id: '/api/scans/',
  path: '/api/scans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScansIdRoute = ApiScansIdRouteImport.update({
  id: '/api/scans/$id',
  path: '/api/scans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsIndexRoute = ApiSettingsIndexRouteImport.update({
  id: '/api/settings/',
  path: '/api/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsStatusRoute = ApiSettingsStatusRouteImport.update({
  id: '/api/settings/status',
  path: '/api/settings/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsIdDownloadRoute = ApiReportsIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => ApiReportsIdRoute,
} as any)
const ApiReviewsIdAnalysisRoute = ApiReviewsIdAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => ApiReviewsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/business/$id': typeof ApiBusinessIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/reviews/$id': typeof ApiReviewsIdRouteWithChildren
  '/api/scan/$id': typeof ApiScanIdRoute
  '/api/scans/$id': typeof ApiScansIdRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/reports/': typeof ApiReportsIndexRoute
  '/api/scan/': typeof ApiScanIndexRoute
  '/api/scans/': typeof ApiScansIndexRoute
  '/api/settings/': typeof ApiSettingsIndexRoute
  '/api/reports/$id/download': typeof ApiReportsIdDownloadRoute
  '/api/reviews/$id/analysis': typeof ApiReviewsIdAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/business/$id': typeof ApiBusinessIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/reviews/$id': typeof ApiReviewsIdRouteWithChildren
  '/api/scan/$id': typeof ApiScanIdRoute
  '/api/scans/$id': typeof ApiScansIdRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/api/reports': typeof ApiReportsIndexRoute
  '/api/scan': typeof ApiScanIndexRoute
  '/api/scans': typeof ApiScansIndexRoute
  '/api/settings': typeof ApiSettingsIndexRoute
  '/api/reports/$id/download': typeof ApiReportsIdDownloadRoute
  '/api/reviews/$id/analysis': typeof ApiReviewsIdAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/business/$id': typeof ApiBusinessIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/reports/$id': typeof ApiReportsIdRouteWithChildren
  '/api/reviews/$id': typeof ApiReviewsIdRouteWithChildren
  '/api/scan/$id': typeof ApiScanIdRoute
  '/api/scans/$id': typeof ApiScansIdRoute
  '/api/settings/status': typeof ApiSettingsStatusRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/api/reports/': typeof ApiReportsIndexRoute
  '/api/scan/': typeof ApiScanIndexRoute
  '/api/scans/': typeof ApiScansIndexRoute
  '/api/settings/': typeof ApiSettingsIndexRoute
  '/api/reports/$id/download': typeof ApiReportsIdDownloadRoute
  '/api/reviews/$id/analysis': typeof ApiReviewsIdAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/api/health'
    | '/reports/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/business/$id'
    | '/api/public/health'
    | '/api/reports/$id'
    | '/api/reviews/$id'
    | '/api/scan/$id'
    | '/api/scans/$id'
    | '/api/settings/status'
    | '/reports/'
    | '/api/reports/'
    | '/api/scan/'
    | '/api/scans/'
    | '/api/settings/'
    | '/api/reports/$id/download'
    | '/api/reviews/$id/analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/api/health'
    | '/reports/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/business/$id'
    | '/api/public/health'
    | '/api/reports/$id'
    | '/api/reviews/$id'
    | '/api/scan/$id'
    | '/api/scans/$id'
    | '/api/settings/status'
    | '/reports'
    | '/api/reports'
    | '/api/scan'
    | '/api/scans'
    | '/api/settings'
    | '/api/reports/$id/download'
    | '/api/reviews/$id/analysis'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/scan'
    | '/_authenticated/settings'
    | '/api/health'
    | '/_authenticated/reports/$id'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/business/$id'
    | '/api/public/health'
    | '/api/reports/$id'
    | '/api/reviews/$id'
    | '/api/scan/$id'
    | '/api/scans/$id'
    | '/api/settings/status'
    | '/_authenticated/reports/'
    | '/api/reports/'
    | '/api/scan/'
    | '/api/scans/'
    | '/api/settings/'
    | '/api/reports/$id/download'
    | '/api/reviews/$id/analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiBusinessIdRoute: typeof ApiBusinessIdRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiReportsIdRoute: typeof ApiReportsIdRouteWithChildren
  ApiReviewsIdRoute: typeof ApiReviewsIdRouteWithChildren
  ApiScanIdRoute: typeof ApiScanIdRoute
  ApiScansIdRoute: typeof ApiScansIdRoute
  ApiSettingsStatusRoute: typeof ApiSettingsStatusRoute
  ApiReportsIndexRoute: typeof ApiReportsIndexRoute
  ApiScanIndexRoute: typeof ApiScanIndexRoute
  ApiScansIndexRoute: typeof ApiScansIndexRoute
  ApiSettingsIndexRoute: typeof ApiSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/business/$id': {
      id: '/api/business/$id'
      path: '/api/business/$id'
      fullPath: '/api/business/$id'
      preLoaderRoute: typeof ApiBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/': {
      id: '/api/reports/'
      path: '/api/reports'
      fullPath: '/api/reports/'
      preLoaderRoute: typeof ApiReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id': {
      id: '/api/reports/$id'
      path: '/api/reports/$id'
      fullPath: '/api/reports/$id'
      preLoaderRoute: typeof ApiReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews/$id': {
      id: '/api/reviews/$id'
      path: '/api/reviews/$id'
      fullPath: '/api/reviews/$id'
      preLoaderRoute: typeof ApiReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/': {
      id: '/api/scan/'
      path: '/api/scan'
      fullPath: '/api/scan/'
      preLoaderRoute: typeof ApiScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan/$id': {
      id: '/api/scan/$id'
      path: '/api/scan/$id'
      fullPath: '/api/scan/$id'
      preLoaderRoute: typeof ApiScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scans/': {
      id: '/api/scans/'
      path: '/api/scans'
      fullPath: '/api/scans/'
      preLoaderRoute: typeof ApiScansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scans/$id': {
      id: '/api/scans/$id'
      path: '/api/scans/$id'
      fullPath: '/api/scans/$id'
      preLoaderRoute: typeof ApiScansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/': {
      id: '/api/settings/'
      path: '/api/settings'
      fullPath: '/api/settings/'
      preLoaderRoute: typeof ApiSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings/status': {
      id: '/api/settings/status'
      path: '/api/settings/status'
      fullPath: '/api/settings/status'
      preLoaderRoute: typeof ApiSettingsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/$id/download': {
      id: '/api/reports/$id/download'
      path: '/download'
      fullPath: '/api/reports/$id/download'
      preLoaderRoute: typeof ApiReportsIdDownloadRouteImport
      parentRoute: typeof ApiReportsIdRoute
    }
    '/api/reviews/$id/analysis': {
      id: '/api/reviews/$id/analysis'
      path: '/analysis'
      fullPath: '/api/reviews/$id/analysis'
      preLoaderRoute: typeof ApiReviewsIdAnalysisRouteImport
      parentRoute: typeof ApiReviewsIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiReportsIdRouteChildren {
  ApiReportsIdDownloadRoute: typeof ApiReportsIdDownloadRoute
}

const ApiReportsIdRouteChildren: ApiReportsIdRouteChildren = {
  ApiReportsIdDownloadRoute: ApiReportsIdDownloadRoute,
}

const ApiReportsIdRouteWithChildren = ApiReportsIdRoute._addFileChildren(
  ApiReportsIdRouteChildren,
)

interface ApiReviewsIdRouteChildren {
  ApiReviewsIdAnalysisRoute: typeof ApiReviewsIdAnalysisRoute
}

const ApiReviewsIdRouteChildren: ApiReviewsIdRouteChildren = {
  ApiReviewsIdAnalysisRoute: ApiReviewsIdAnalysisRoute,
}

const ApiReviewsIdRouteWithChildren = ApiReviewsIdRoute._addFileChildren(
  ApiReviewsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiBusinessIdRoute: ApiBusinessIdRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiReportsIdRoute: ApiReportsIdRouteWithChildren,
  ApiReviewsIdRoute: ApiReviewsIdRouteWithChildren,
  ApiScanIdRoute: ApiScanIdRoute,
  ApiScansIdRoute: ApiScansIdRoute,
  ApiSettingsStatusRoute: ApiSettingsStatusRoute,
  ApiReportsIndexRoute: ApiReportsIndexRoute,
  ApiScanIndexRoute: ApiScanIndexRoute,
  ApiScansIndexRoute: ApiScansIndexRoute,
  ApiSettingsIndexRoute: ApiSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
